// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwzuyyqnozmioydvrbid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3enV5eXFub3ptaW95ZHZyYmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTM1OTIsImV4cCI6MjA2OTI4OTU5Mn0.a1dVx7J7U89T7rcNt8f-0dBxfRS2HAf-uJxo1kwDN0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});